name: Auto Version on PR merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show HEAD
      run: git show HEAD:sub/version.cs

    - name: Parse and increase version
      run: |
        ### Parse
        # get last version from the latest commit
        version_curr=$(git show HEAD:sub/version.cs | grep -oP 'public const string version = "\K[^"]+')
        echo "version curr: $version_curr"

        # split version_curr
        IFS='.' read -r -a version_curr_parts <<< "$version_curr"
        echo "version_curr_parts[0]: ${version_curr_parts[0]}"
        echo "version_curr_parts[1]: ${version_curr_parts[1]}"
        echo "version_curr_parts[2]: ${version_curr_parts[2]}"

        # get version_product
        version_product=${version_curr_parts[0]}
        echo "version_product: $version_product"

        # get current date
        year=$(TZ="Asia/Seoul" date +"%y")
        month=$(TZ="Asia/Seoul" date +"%m")
        day=$(TZ="Asia/Seoul" date +"%d")
        echo "year: $year"
        echo "month: $month"
        echo "day: $day"

        # get version_curr_seq
        version_curr_seq="${version_curr_parts[2]: -1}"
        echo "version_curr_seq: $version_curr_seq"

        ### Increase
        version_next_seq=$((version_curr_seq + 1))
        echo "version_next_seq: $version_next_seq"

        ### Finally
        version_next="${version_product}.${year}.${month}${day}${version_next_seq}"
        echo "version next: $version_next"

    - name: Update version in version.cs
      run: |
        sed "s/public const string version = \"\([0-9]\+\)\"/$new_version/" sub/version.cs
        sed -i "s/public const string version = \"\([0-9]\+\)\"/$new_version/" sub/version.cs

    - name: Commit and push with next version
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add sub/version.cs
        git add manifest.xml
        git commit -m "Update version to $version_next"
        git push origin main
        #TODO: implement identical logic on manifest.xml file
